export type QuantizationType = 'FP32' | 'FP16' | 'INT8' | 'INT4';
export type NodeStatusType = 'idle' | 'training' | 'aggregating' | 'completed' | 'offline';
export type AggregationStrategy = 'FedAvg' | 'FedProx' | 'FedAMP';
export type CnnModelType = 'MobileNet-V3' | 'ResNet-18' | 'EfficientNet-B0';

export interface FederatedNode {
  id: string;
  name: string;
  device: string;
  status: NodeStatusType;
  quantization: QuantizationType;
  localLoss: number;
  accuracy: number;
  latency: number; // ms
  bandwidth: number; // Mbps
  power: number; // mW
  samplesProcessed: number;
  batteryLevel?: number;
  nodeType?: 'edge' | 'cloud' | 'mobile';
  history?: {
    loss: number[];
    accuracy: number[];
    latency: number[];
  };
}

export interface PipelineConfig {
  activeQuantization: QuantizationType;
  nodesCount: number;
  rounds: number;
  learningRate: number;
  aggregationStrategy: AggregationStrategy;
  cnnModel: CnnModelType;
  noiseMultiplier: number; // Differential Privacy multiplier
  targetTask: string; // e.g. "Industrial Anomaly Detection", "Autonomous Navigation"
  zeta?: number; // Privacy budget scaling parameter
  syncFrequency?: number; // Sync frequency (epochs)
  communicationCompression?: number; // Sparsification/Compression %
}

export interface SimulationHistoryPoint {
  round: number;
  globalLoss: number;
  ganLossG: number;
  ganLossD: number;
  cnnAccuracy: number;
  compressionRatio: number;
  avgLatency: number;
}

export interface WeightLayer {
  layerName: string;
  weightsFP32: number[];
  weightsQuantized: number[];
  clippingThreshold: number;
  qScale: number;
  qZeroPoint: number;
}

export interface User {
  username: string;
  token: string;
  isolatedFolder: string;
}

export interface UserUpload {
  id: string;
  name: string;
  username: string;
  filepath: string;
  fileSizeBytes: number;
  timestamp: string;
  predictions: Array<{ label: string; confidence: number }>;
  inferenceTimeMs: number;
  quantizationErrorPct: number;
  modelName: string;
  quantization: QuantizationType;
  associatedNodeId?: string;
}

export interface PipelineStepState {
  rawImage: string; // Base64 or placeholder URL
  ganGeneratedImage: string; // Synthetic image generated by the GAN generator
  cnnFeatureMap: string; // Visualized activations
  predictions: Array<{ label: string; confidence: number }>;
  inferenceTimeMs: number;
  quantizationErrorPct: number;
}

export interface AdvisorRecommendation {
  summary: string;
  nodesScore: number; // 0-100 rating of current node setup
  quantizationAnalysis: string;
  ganStabilityIndex: number; // 0-100
  differentialPrivacyReport: string;
  suggestedSteps: string[];
}
